version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.4.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: bundle
          command: npm run build:prod
      - deploy:
          command: |
            GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
            gsutil cp -r dist gs://static.dashgithub.com


